### ISSUE TITLE
Failed to run compilers on quokka.js, Error: Plugin/Preset files are not allowed to export objects, only functions. 

### ISSUE THREAD

**Issue by Ridermansb** [wallabyjs/quokka-react-sample#2]
```
({
  babel: true,
  plugins: ["jsdom-quokka-plugin"]
});

import React from "react";
import ReactDOM from "react-dom";

document.body.innerHTML += `<div id="root"></div>`;

ReactDOM.render(<h1>Hello, world!</h1>, document.getElementById("root"));

const root = document.getElementById("root").innerHTML;
root;

```

**Comment by smcenlly** [comment]
This error can occur when you have multiple versions of babel installed by your dependencies. You can check this by looking at your `node_modules` directory. If you have multiple versions installed, you will have `@babel/core` (version 7) and `babel-core` (version 6).

By default, quokka will try and use the latest version.  You can override these in your quokka configuration (you can read more about configuration [here](https://quokkajs.com/docs/configuration.html)).

You can force your project to use version 6 (which should solve your problem), by specifying the babel path in your configuration file (note, this is absolute or relative to the project’s folder):

```
{
    babel: {
        path: "./node_modules/babel-core"
    }
}
```
